# Generated by Django 4.2.1 on 2023-05-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_champ_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='champ',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
