# Generated by Django 4.2.1 on 2023-05-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_champ_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='champ',
            name='image',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
