# Generated by Django 4.2.1 on 2023-05-31 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_champ_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='champ',
            options={'ordering': ['name']},
        ),
    ]
