# Generated by Django 4.2.1 on 2023-06-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_remove_champ_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='champ',
            name='splash',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
