# Generated by Django 4.2.1 on 2023-06-05 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_lane'),
    ]

    operations = [
        migrations.AddField(
            model_name='champ',
            name='lane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hello.lane'),
        ),
    ]
