# Generated by Django 4.2.1 on 2023-06-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_champ_lane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champ',
            name='lane',
        ),
        migrations.AddField(
            model_name='champ',
            name='lane',
            field=models.ManyToManyField(to='hello.lane'),
        ),
    ]
