# Generated by Django 4.2.1 on 2023-06-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_remove_champ_lane_champ_lane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lane',
            name='lane',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
